required_python_version_minimum: 3.9.5

scenarios_file: solution/macroalgaerestoration/scenario_inputs.json
PDS_adoption_file: solution/macroalgaerestoration/unit_adoption_data/custom_pds_adoption.json
REF_adoption_file: solution/macroalgaerestoration/unit_adoption_data/custom_ref_adoption.json
base_year: 2014
start_year: 2020
end_year: 2050
total_area: 198
total_area_as_of_period: 2018
change_per_period: 0.0
delay_impact_of_protection_by_one_year: True
delay_regrowth_of_degraded_land_by_one_year: False
