"""workbook updates

Revision ID: 0b4d7724f81b
Revises: 82f30644e97d
Create Date: 2020-12-21 13:38:19.011310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b4d7724f81b'
down_revision = '82f30644e97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('reference', 'json')
    op.add_column('scenario', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('scenario', 'json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('scenario', 'data')
    op.add_column('reference', sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('reference', 'data')
    # ### end Alembic commands ###
