"""workbook updates

Revision ID: 232c800129ef
Revises: 0418f26e5be2
Create Date: 2020-12-18 14:16:13.976904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232c800129ef'
down_revision = '0418f26e5be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('control_id', sa.Integer(), nullable=True))
    op.add_column('workbook', sa.Column('scenario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workbook', 'scenario', ['scenario_id'], ['id'])
    op.create_foreign_key(None, 'workbook', 'control', ['control_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workbook', type_='foreignkey')
    op.drop_constraint(None, 'workbook', type_='foreignkey')
    op.drop_column('workbook', 'scenario_id')
    op.drop_column('workbook', 'control_id')
    # ### end Alembic commands ###
