"""workbook updates

Revision ID: 2524d9bf1bbc
Revises: 0b4d7724f81b
Create Date: 2020-12-21 13:53:56.591373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2524d9bf1bbc'
down_revision = '0b4d7724f81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variation', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('variation', 'reference_parent_path')
    op.drop_column('variation', 'overrides')
    op.drop_column('variation', 'scenario_parent_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variation', sa.Column('scenario_parent_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('variation', sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variation', sa.Column('reference_parent_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('variation', 'data')
    # ### end Alembic commands ###
