"""workbooks

Revision ID: 257f3bd59468
Revises: f012b95d4ef7
Create Date: 2020-12-16 10:55:08.494506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '257f3bd59468'
down_revision = 'f012b95d4ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variation_id'), 'variation', ['id'], unique=False)
    op.create_table('workbook_variation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=True),
    sa.Column('variation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['variation.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workbook_variation_id'), 'workbook_variation', ['id'], unique=False)
    op.drop_table('technology')
    op.add_column('workbook', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('workbook', sa.Column('end_year', sa.Integer(), nullable=True))
    op.add_column('workbook', sa.Column('name', sa.String(), nullable=True))
    op.add_column('workbook', sa.Column('start_year', sa.Integer(), nullable=True))
    op.add_column('workbook', sa.Column('ui', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_workbook_id'), 'workbook', ['id'], unique=False)
    op.drop_constraint('workbook_user_id_fkey', 'workbook', type_='foreignkey')
    op.create_foreign_key(None, 'workbook', 'user', ['author_id'], ['id'])
    op.drop_column('workbook', 'data')
    op.drop_column('workbook', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workbook', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workbook', type_='foreignkey')
    op.create_foreign_key('workbook_user_id_fkey', 'workbook', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_workbook_id'), table_name='workbook')
    op.drop_column('workbook', 'ui')
    op.drop_column('workbook', 'start_year')
    op.drop_column('workbook', 'name')
    op.drop_column('workbook', 'end_year')
    op.drop_column('workbook', 'author_id')
    op.create_table('technology',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='technology_pkey')
    )
    op.drop_index(op.f('ix_workbook_variation_id'), table_name='workbook_variation')
    op.drop_table('workbook_variation')
    op.drop_index(op.f('ix_variation_id'), table_name='variation')
    op.drop_table('variation')
    # ### end Alembic commands ###
