"""region to list

Revision ID: 2c4ed49bdf0c
Revises: 791fb4c9bfab
Create Date: 2021-01-21 16:35:40.802474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c4ed49bdf0c'
down_revision = '791fb4c9bfab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('regions', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('workbook', 'region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workbook', 'regions')
    # ### end Alembic commands ###
