"""vma_csv binary table

Revision ID: 2e975775197f
Revises: af20fe07d323
Create Date: 2021-01-27 14:37:58.650545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e975775197f'
down_revision = 'af20fe07d323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
