"""variation schema change

Revision ID: 752e3bbb4472
Revises: b2907312748f
Create Date: 2021-01-06 08:21:32.445966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752e3bbb4472'
down_revision = 'b2907312748f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
