"""workbooks

Revision ID: 7792f854cf99
Revises: fc61e7fb4d9a
Create Date: 2020-12-16 16:22:16.435797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7792f854cf99'
down_revision = 'fc61e7fb4d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
