"""adding region to workbook

Revision ID: 791fb4c9bfab
Revises: b618b6633beb
Create Date: 2021-01-21 16:15:35.191315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791fb4c9bfab'
down_revision = 'b618b6633beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbook', 'region')
    # ### end Alembic commands ###
