"""reference table

Revision ID: 7b95146771e9
Revises: 6c5df3029152
Create Date: 2020-12-17 13:38:25.584300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b95146771e9'
down_revision = '6c5df3029152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_reference_name'), 'technology_reference', ['name'], unique=False)
    op.drop_index('ix_variation_id', table_name='variation')
    op.drop_table('variation')
    op.drop_index('ix_workbook_variation_id', table_name='workbook_variation')
    op.drop_table('workbook_variation')
    op.add_column('workbook', sa.Column('variation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbook', 'variation')
    op.create_table('workbook_variation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workbook_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['variation.id'], name='workbook_variation_variation_id_fkey'),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], name='workbook_variation_workbook_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workbook_variation_pkey')
    )
    op.create_index('ix_workbook_variation_id', 'workbook_variation', ['id'], unique=False)
    op.create_table('variation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='variation_pkey')
    )
    op.create_index('ix_variation_id', 'variation', ['id'], unique=False)
    op.drop_index(op.f('ix_technology_reference_name'), table_name='technology_reference')
    op.drop_table('technology_reference')
    # ### end Alembic commands ###
