"""adding created_at and updated_at to workbook

Revision ID: 8281a1a64c37
Revises: 903c464b22d9
Create Date: 2021-03-10 20:46:25.757399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8281a1a64c37'
down_revision = '903c464b22d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('created_at', sa.DateTime()))
    op.add_column('workbook', sa.Column('updated_at', sa.DateTime()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbook', 'updated_at')
    op.drop_column('workbook', 'created_at')
    # ### end Alembic commands ###
