"""workbook updates

Revision ID: 82f30644e97d
Revises: 6b7b9069b417
Create Date: 2020-12-21 13:25:14.458951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f30644e97d'
down_revision = '6b7b9069b417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
