"""adding description to workbook

Revision ID: 903c464b22d9
Revises: 9d1c5560c50b
Create Date: 2021-03-04 21:13:49.717462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903c464b22d9'
down_revision = '9d1c5560c50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbook', 'description')
    # ### end Alembic commands ###
