"""variation schema change

Revision ID: 9b300eca29b6
Revises: 752e3bbb4472
Create Date: 2021-01-06 08:27:07.530050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b300eca29b6'
down_revision = '752e3bbb4472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
