"""adding meta column to user

Revision ID: 9d1c5560c50b
Revises: 0f335f086310
Create Date: 2021-02-04 11:50:54.784568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d1c5560c50b'
down_revision = '0f335f086310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'meta')
    # ### end Alembic commands ###
