"""vma_csv binary table

Revision ID: af20fe07d323
Revises: e642eecb5116
Create Date: 2021-01-27 14:36:19.898884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af20fe07d323'
down_revision = 'e642eecb5116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vma_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('technology', sa.String(), nullable=True),
    sa.Column('variable', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vma_csv_name'), 'vma_csv', ['name'], unique=False)
    op.add_column('workbook', sa.Column('vma_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbook', 'vma_sources')
    op.drop_index(op.f('ix_vma_csv_name'), table_name='vma_csv')
    op.drop_table('vma_csv')
    # ### end Alembic commands ###
