"""variation schema change

Revision ID: b2907312748f
Revises: ccf37d1bbc5b
Create Date: 2021-01-06 08:18:49.216262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2907312748f'
down_revision = 'ccf37d1bbc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
