"""resource tables

Revision ID: b618b6633beb
Revises: a8476769cae0
Create Date: 2021-01-20 11:56:33.186032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b618b6633beb'
down_revision = 'a8476769cae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_data_name'), 'adoption_data', ['name'], unique=False)
    op.create_table('ca_pds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ca_pds_name'), 'ca_pds', ['name'], unique=False)
    op.create_table('ca_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ca_ref_name'), 'ca_ref', ['name'], unique=False)
    op.create_table('tam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tam_name'), 'tam', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tam_name'), table_name='tam')
    op.drop_table('tam')
    op.drop_index(op.f('ix_ca_ref_name'), table_name='ca_ref')
    op.drop_table('ca_ref')
    op.drop_index(op.f('ix_ca_pds_name'), table_name='ca_pds')
    op.drop_table('ca_pds')
    op.drop_index(op.f('ix_adoption_data_name'), table_name='adoption_data')
    op.drop_table('adoption_data')
    # ### end Alembic commands ###
