"""workbook versioning

Revision ID: ccf37d1bbc5b
Revises: 5d431df3e3d3
Create Date: 2021-01-05 15:15:01.200243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccf37d1bbc5b'
down_revision = '5d431df3e3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('version', sa.Integer(), nullable=True))
    op.drop_column('workbook', 'commit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('commit', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('workbook', 'version')
    # ### end Alembic commands ###
