"""has_changed on workbook

Revision ID: e642eecb5116
Revises: 2c4ed49bdf0c
Create Date: 2021-01-27 10:30:37.568743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e642eecb5116'
down_revision = '2c4ed49bdf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbook', sa.Column('has_run', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbook', 'has_run')
    # ### end Alembic commands ###
