"""variation schema change

Revision ID: f68beb524a30
Revises: 9b300eca29b6
Create Date: 2021-01-06 08:30:52.598921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68beb524a30'
down_revision = '9b300eca29b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
