"""scenario models

Revision ID: fc61e7fb4d9a
Revises: 257f3bd59468
Create Date: 2020-12-16 16:00:10.708789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc61e7fb4d9a'
down_revision = '257f3bd59468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_scenario_name'), 'technology_scenario', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technology_scenario_name'), table_name='technology_scenario')
    op.drop_table('technology_scenario')
    # ### end Alembic commands ###
