required_python_version_minimum: 3.9.5

scenarios_file: solution/seagrassrestoration/scenario_inputs.json
PDS_adoption_file: solution/seagrassrestoration/unit_adoption_data/custom_pds_adoption.json
REF_adoption_file: solution/seagrassrestoration/unit_adoption_data/custom_ref_adoption.json
base_year: 2014
start_year: 2020
end_year: 2050