import json
import sys

# Taken from Regions-Countries sorting tab of Excel model, with several changes:
# + Add various aliases for names of countries in the JSON source material.
# + change "OECD90 / EU" results to "OECD90"
# + change "Eastern Europe / EU" results to "Eastern Europe"
region_mapping = {
    "Afghanistan": "Asia (Sans Japan)",
    "Akrotiri": "Not included",
    "Aland": "Not included",
    "Aland Islands": "Not included",
    "Åland Islands": "Not included",
    "Albania": "Eastern Europe",
    "Algeria": "Middle East and Africa",
    "American Samoa": "Asia (Sans Japan)",
    "Andorra": "OECD90",
    "Angola": "Middle East and Africa",
    "Anguilla": "Latin America",
    "Antarctica": "Not included",
    "Antigua and Barbuda": "Latin America",
    "Antilles (Netherlands)": "Latin America",
    "Argentina": "Latin America",
    "Armenia": "Eastern Europe",
    "Aruba": "Latin America",
    "Australia": "OECD90",
    "Austria": "EU",
    "Azerbaijan": "Eastern Europe",
    "Bahamas": "Latin America",
    "The Bahamas": "Latin America",
    "Bahrain": "Middle East and Africa",
    "Baikonur": "Eastern Europe",
    "Bangladesh": "Asia (Sans Japan)",
    "Barbados": "Latin America",
    "Belarus": "Eastern Europe",
    "Belgium": "EU",
    "Belize": "Latin America",
    "Benin": "Middle East and Africa",
    "Bermuda": "Latin America",
    "Bhutan": "Asia (Sans Japan)",
    "Bolivia (Plurinational State of)": "Latin America",
    "Bolivia": "Latin America",
    "Bolivia, Plurinational State of": "Latin America",
    "Bosnia and Herzegovina": "Eastern Europe",
    "Bosnia and Herz.": "Eastern Europe",
    "Botswana": "Middle East and Africa",
    "Brazil": "Latin America",
    "British Indian Ocean Territory": "Not included",
    "British Virgin Islands": "Latin America",
    "Virgin Islands, British": "Latin America",
    "Brunei Darussalam": "Asia (Sans Japan)",
    "Brunei": "Asia (Sans Japan)",
    "Bulgaria": "EU",
    "Burkina Faso": "Middle East and Africa",
    "Burundi": "Middle East and Africa",
    "Cambodia": "Asia (Sans Japan)",
    "Cameroon": "Middle East and Africa",
    "Canada": "OECD90",
    "Cape Verde": "Middle East and Africa",
    "Cayman Islands": "Latin America",
    "Central African Republic": "Middle East and Africa",
    "Central African Rep.": "Middle East and Africa",
    "Chad": "Middle East and Africa",
    "Channel Islands": "OECD90",
    "Chile": "Latin America",
    "China": "China",
    "Christmas Island": "Not included",
    "Cocos Islands": "Not included",
    "Colombia": "Latin America",
    "Comoros": "Middle East and Africa",
    "Congo": "Middle East and Africa",
    "Congo, the Democratic Republic of the": "Middle East and Africa",
    "Republic of the Congo": "Middle East and Africa",
    "Cook Islands": "Not included",
    "Costa Rica": "Latin America",
    "Côte d'Ivoire": "Middle East and Africa",
    "Croatia": "EU",
    "Cuba": "Latin America",
    "Curaçao": "Latin America",
    "Cyprus": "EU",
    "Cyprus U.N. Buffer Zone": "Eastern Europe",
    "Northern Cyprus": "Eastern Europe",
    "Czech Republic": "EU",
    "Czech Rep.": "EU",
    "Democratic People's Republic of Korea": "Asia (Sans Japan)",
    "Dem. Rep. Korea": "Asia (Sans Japan)",
    "Korea, Democratic People's Republic of": "Asia (Sans Japan)",
    "North Korea": "Asia (Sans Japan)",
    "Democratic Republic of the Congo": "Middle East and Africa",
    "Dem. Rep. Congo": "Middle East and Africa",
    "Denmark": "EU",
    "Dhekelia": "Eastern Europe",
    "Djibouti": "Middle East and Africa",
    "Dominica": "Not included",
    "Dominican Republic": "Latin America",
    "Dominican Rep.": "Latin America",
    "East Timor": "Asia (Sans Japan)",
    "Timor-Leste": "Asia (Sans Japan)",
    "Ecuador": "Latin America",
    "Egypt": "Middle East and Africa",
    "El Salvador": "Latin America",
    "Equatorial Guinea": "Middle East and Africa",
    "Eq. Guinea": "Middle East and Africa",
    "Eritrea": "Middle East and Africa",
    "Estonia": "EU",
    "Ethiopia": "Middle East and Africa",
    "Falkland Islands (Malvinas)": "Latin America",
    "Falkland Is.": "Latin America",
    "Falkland Islands": "Latin America",
    "Faroe Islands": "OECD90",
    "Faeroe Is.": "OECD90",
    "Fiji": "OECD90",
    "Finland": "EU",
    "Fr. S. Antarctic Lands": "Not included",
    "French Southern Territories": "Not included",
    "French Southern and Antarctic Lands": "Not included",
    "France": "EU",
    "French Guiana": "Latin America",
    "French Polynesia": "OECD90",
    "Fr. Polynesia": "OECD90",
    "Gabon": "Middle East and Africa",
    "Gambia": "Middle East and Africa",
    "Georgia": "Eastern Europe",
    "Germany": "EU",
    "Ghana": "Middle East and Africa",
    "Gibraltar": "OECD90",
    "Greece": "EU",
    "Greenland": "OECD90",
    "Grenada": "Not included",
    "Guadeloupe": "Latin America",
    "Guam": "OECD90",
    "Guatemala": "Latin America",
    "Guernsey": "OECD90",
    "Guinea": "Middle East and Africa",
    "Guinea-Bissau": "Middle East and Africa",
    "Guinea Bissau": "Middle East and Africa",
    "Guyana": "Latin America",
    "Haiti": "Latin America",
    "Heard I. and McDonald Is.": "Not included",
    "Heard Island and McDonald Islands": "Not included",
    "Honduras": "Latin America",
    "Hong Kong": "Asia (Sans Japan)",
    "Hungary": "EU",
    "Iceland": "OECD90",
    "India": "India",
    "Indonesia": "Asia (Sans Japan)",
    "Iran (Islamic Republic of)": "Middle East and Africa",
    "Iran": "Middle East and Africa",
    "Iran, Islamic Republic of": "Middle East and Africa",
    "Iraq": "Middle East and Africa",
    "Ireland": "EU",
    "Isle of Man": "OECD90",
    "Israel": "Middle East and Africa",
    "Italy": "EU",
    "Ivory Coast": "Middle East and Africa",
    "Jamaica": "Latin America",
    "Japan": "OECD90",
    "Jersey": "Not included",
    "Jordan": "Middle East and Africa",
    "Kazakhstan": "Eastern Europe",
    "Kenya": "Middle East and Africa",
    "Kiribati": "Not included",
    "Korea": "Asia (Sans Japan)",
    "Republic of Korea (South Korea)": "Asia (Sans Japan)",
    "Korea, Republic of": "Asia (Sans Japan)",
    "South Korea": "Asia (Sans Japan)",
    "Kosovo": "Eastern Europe",
    "Kuwait": "Middle East and Africa",
    "Kyrgyzstan": "Eastern Europe",
    "Lao People's Democratic Republic": "Asia (Sans Japan)",
    "Lao PDR": "Asia (Sans Japan)",
    "Laos": "Asia (Sans Japan)",
    "Latvia": "EU",
    "Lebanon": "Middle East and Africa",
    "Lesotho": "Middle East and Africa",
    "Liberia": "Middle East and Africa",
    "Libya": "Middle East and Africa",
    "Liechtenstein": "Not included",
    "Lithuania": "EU",
    "Luxembourg": "EU",
    "Macao": "Asia (Sans Japan)",
    "The former Yugoslav Republic of Macedonia": "Eastern Europe",
    "Macedonia": "Eastern Europe",
    "Macedonia, the former Yugoslav Republic of": "Eastern Europe",
    "Madagascar": "Middle East and Africa",
    "Malawi": "Middle East and Africa",
    "Malaysia": "Asia (Sans Japan)",
    "Maldives": "Asia (Sans Japan)",
    "Mali": "Middle East and Africa",
    "Malta": "EU",
    "Marshall Islands": "Not included",
    "Martinique": "Latin America",
    "Mauritania": "Middle East and Africa",
    "Mauritius": "Middle East and Africa",
    "Mayotte": "Middle East and Africa",
    "Mexico": "Latin America",
    "Micronesia (Federated States of)": "Not included",
    "Micronesia": "Not included",
    "Micronesia, Federated States of": "Not included",
    "Republic of Moldova": "Eastern Europe",
    "Moldova": "Eastern Europe",
    "Moldova, Republic of": "Eastern Europe",
    "Mongolia": "Asia (Sans Japan)",
    "Monaco": "Not included",
    "Montenegro": "Eastern Europe",
    "Montserrat": "Latin America",
    "Morocco": "Middle East and Africa",
    "Mozambique": "Middle East and Africa",
    "Myanmar": "Asia (Sans Japan)",
    "Namibia": "Middle East and Africa",
    "Nauru": "Not included",
    "Nepal": "Asia (Sans Japan)",
    "Netherlands": "EU",
    "Netherlands Antilles / Curacao": "Latin America",
    "New Caledonia": "OECD90",
    "New Zealand": "OECD90",
    "Nicaragua": "Latin America",
    "Niger": "Middle East and Africa",
    "Nigeria": "Middle East and Africa",
    "Niue": "Not included",
    "Norfolk Island": "Asia (Sans Japan)",
    "N. Cyprus": "Eastern Europe",
    "Northern Mariana Islands": "Asia (Sans Japan)",
    "Norway": "OECD90",
    "Oman": "Middle East and Africa",
    "Pakistan": "Asia (Sans Japan)",
    "Palau": "Not included",
    "Palestine": "Middle East and Africa",
    "Palestine, State of": "Middle East and Africa",
    "Panama": "Latin America",
    "Papua New Guinea": "Asia (Sans Japan)",
    "Paraguay": "Latin America",
    "Peru": "Latin America",
    "Philippines": "Asia (Sans Japan)",
    "Pitcairn Islands": "Asia (Sans Japan)",
    "Pitcairn": "Asia (Sans Japan)",
    "Poland": "EU",
    "Portugal": "EU",
    "Puerto Rico": "Latin America",
    "Qatar": "Middle East and Africa",
    "Reunion": "Middle East and Africa",
    "Romania": "EU",
    "Russian Federation": "Eastern Europe",
    "Russia": "Eastern Europe",
    "Rwanda": "Middle East and Africa",
    "Saint Helena, Ascension and Tristan da Cunha": "Middle East and Africa",
    "Saint Kitts and Nevis": "Not included",
    "Saint Lucia": "Not included",
    "Saint Pierre and Miquelon": "OECD90",
    "Saint Vincent and the Grenadines": "Not included",
    "St. Vin. and Gren.": "Not included",
    "Samoa": "OECD90",
    "San Marino": "Not included",
    "Sao Tome and Principe": "Not included",
    "São Tomé and Principe": "Not included",
    "Saudi Arabia": "Middle East and Africa",
    "Senegal": "Middle East and Africa",
    "Serbia": "Eastern Europe",
    "Republic of Serbia": "Eastern Europe",
    "Seychelles": "Not included",
    "Siachen Glacier": "Not included",
    "Sierra Leone": "Middle East and Africa",
    "Singapore": "Asia (Sans Japan)",
    "Slovakia": "EU",
    "Slovenia": "EU",
    "Solomon Islands": "OECD90",
    "Solomon Is.": "OECD90",
    "Somalia": "Middle East and Africa",
    "Somaliland": "Middle East and Africa",
    "South Africa": "Middle East and Africa",
    "S. Geo. and S. Sandw. Is.": "Not included",
    "South Georgia and the South Sandwich Islands": "Not included",
    "South Sudan": "Middle East and Africa",
    "S. Sudan": "Middle East and Africa",
    "Spain": "EU",
    "Sri Lanka": "Asia (Sans Japan)",
    "St-Martin": "Latin America",
    "Saint Martin (French part)": "Latin America",
    "Sint Maarten": "Latin America",
    "Sint Maarten (Dutch part)": "Latin America",
    "Saint Barthélemy": "Latin America",
    "Sudan": "Middle East and Africa",
    "Suriname": "Latin America",
    "Swaziland": "Middle East and Africa",
    "Sweden": "EU",
    "Switzerland": "OECD90",
    "Syrian Arab Republic": "Middle East and Africa",
    "Syria": "Middle East and Africa",
    "Tahiti": "Not included",
    "Taiwan": "Asia (Sans Japan)",
    "Taiwan, Province of China": "Asia (Sans Japan)",
    "Tajikistan": "Eastern Europe",
    "United Republic of Tanzania": "Middle East and Africa",
    "Tanzania": "Middle East and Africa",
    "Tanzania, United Republic of": "Middle East and Africa",
    "Thailand": "Asia (Sans Japan)",
    "Togo": "Middle East and Africa",
    "Tokelau": "Not included",
    "Tonga": "Not included",
    "Trinidad and Tobago": "Latin America",
    "Tunisia": "Middle East and Africa",
    "Turkey": "OECD90",
    "Turkmenistan": "Eastern Europe",
    "Turks and Caicos Islands": "Latin America",
    "Tuvalu": "Not included",
    "Uganda": "Middle East and Africa",
    "Ukraine": "Eastern Europe",
    "United Arab Emirates": "Middle East and Africa",
    "United Kingdom": "EU",
    "United States of America": "USA",
    "United States": "USA",
    "United States Virgin Islands": "Latin America",
    "Virgin Islands, U.S.": "Latin America",
    "Uruguay": "Latin America",
    "USNB Guantanamo Bay": "Not included",
    "Uzbekistan": "Eastern Europe",
    "Vanuatu": "OECD90",
    "Vatican": "Not included",
    "Venezuela (Bolivarian Republic of)": "Latin America",
    "Venezuela": "Latin America",
    "Venezuela, Bolivarian Republic of": "Latin America",
    "Viet Nam": "Asia (Sans Japan)",
    "Vietnam": "Asia (Sans Japan)",
    "Wallis and Futuna Islands": "Asia (Sans Japan)",
    "Wallis and Futuna": "Asia (Sans Japan)",
    "West Bank": "Middle East and Africa",
    "Western Sahara": "Middle East and Africa",
    "W. Sahara": "Middle East and Africa",
    "Yemen": "Middle East and Africa",
    "Yugoslavia": "Eastern Europe",
    "Zambia": "Middle East and Africa",
    "Zimbabwe": "Middle East and Africa",
}

d = json.load(sys.stdin)
for country in d['objects']['countries1']['geometries']:
    name = country['properties']['name']
    region = region_mapping[name]
    country['dd_region'] = region

json.dump(obj=d, fp=sys.stdout, indent=2)
