name: docs_pages_workflow
 
                         # execute this workflow when...
on:
  push:                  # we push to develop, or...
    branches: [ develop ]
  workflow_dispatch:     # we select the action manually from the github console
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
 
    - name: Install git and clone repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash
 
    - name: Where are we
      run: |
       pwd
       ls -la
      shell: bash
      
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "./solutions/Documentation/sphinx/buildDocs.sh"
      shell: bash
