# This is a basic workflow to help you get started with Actions

name: Hello World
on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout develop
        uses: actions/checkout@v2

      - name: copy Documentation folder
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: Documentation/
      
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: install dependencies 
        run: pip install pdoc -r requirements.txt
      
      - name: did something?
        run: pdoc --version

  publish-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: checkout gh_pages
        uses: actions/checkout@v2
        with:
          ref: gh_pages
      - name: overwrite from copy-job
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs
      - name: commit
        uses: EndBug/add-and-commit@v7
        with:
          add: docs
          branch: gh_pages
